apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: msms-deployment
  labels:
    app: msms-deployment
  namespace: brtc-test-latest
spec:
  template:
    metadata:
      name: msms
      labels:
        app: msms-pod
    spec:
      nodeSelector:
        ms: ms
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      volumes:
        - name: ip-volume
          emptyDir: {}
      containers:
        - name: msms
          image: registry.cn-beijing.aliyuncs.com/webrtc-boom/msms:rtcs-v0.4-newms2-k8s
          env:
          - name: CONFIG_APOLLO_SECRET
            value: 9d01995713a448bf9ad1b9db56f35e64
          - name: CONFIG_APOLLO_URL
            value: http://apollo-dev.baijiayun.com:8080
          - name: CONFIG_APOLLO_APPID
            value: K8sConfig
          - name: CONFIG_APOLLO_CLUSTER
            value: DEV
          - name: CONFIG_APOLLO_NAMESPACE
            value: ms2_conf.json
          - name: CONFIG_APOLLO_BACKUP_PATH
            value: ./
          - name: MALLOC_TRIM_THRESHOLD_
            value: "65535"
          - name: MALLOC_MMAP_THRESHOLD_
            value: "65535"
          - name: CFG_CENTER
            value: "TRUE"
          - name: MS_PORT
            value: "10007"
          - name: GET_CONTAINER_CMD
            value: "cat /proc/self/cgroup | head -1|cut -d/ -f 5|cut -d- -f 2|cut -d. -f 1"
          - name: PUB_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: INNER_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: PULLER_URL
            value: "http://bj-puller-service:8992"
          volumeMounts:
            - name: ip-volume
              mountPath: /var/lib/externalIp
        - name: pubip
          image: harbor.baijiayun.com/sidecar/pubip:0.0.1 
          env:
          - name: APISERVER
            value: https://10.16.31.251:6443
          - name: TOKEN
            value: 'eyJhbGciOiJSUzI1NiIsImtpZCI6Ik9WUWNtSGw4RG5GOVFURkVLZXJ3anh1U2o0MEVLY0x3eGo2UUw0QnR1WlEifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlc3BoZXJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJrdWJlc3BoZXJlLXRva2VuLWs3Y3NiIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6Imt1YmVzcGhlcmUiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiJhYzMwNmYyNy05YmMyLTRhYzEtYTgyNi05OTMyNGI5OTQ4ZjEiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZXNwaGVyZS1zeXN0ZW06a3ViZXNwaGVyZSJ9.hoaIkwAsAlVpSDsas8ltHR4DzGwXrmu0YFUepWJo9ERAHNOKFP9p3nAlgqUeIYtKqlGRl3t6UHZjofH8bLvkug-LKqPbO7AGXzO44FiqSCdkZkoXqkPf5FeWui1axSGUPa68enuMBQRZbw6Q4vrURiGxiv80Ruy13LFmfQcHNxPr5lhea63gvbsUz1TpoH16vO2i7etYK7hr0e1t-sGdHbreVMOd9Gz4Kar62s7t-Pn9NmQo1W-t1b4e39OyIEuDnnt1gJglcvHSj9y0YMFy-mZmKjSql4ZUg2bt9WRJckzlRxuopMBMAlOruo3gp_WrIcYvgYXEfOL97TdbUZK6Tw'
          - name: NodeName
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
            # value: 'bjy-idc-brtc-laliu-test0209'
            volumeMounts:
            - name: ip-volume
              mountPath: /root/externalIp
  selector:
    matchLabels:
      app: msms-pod
---
apiVersion: v1
kind: Service
metadata:
  name: msms-service
  namespace: brtc-test-latest
spec:
  type: NodePort
  selector:
    app: msms-pod
  ports:
    - targetPort: 10006
      port: 10006