apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: ingress-path
 annotations:
   kubernetes.io/ingress.class: "nginx" #指定ingressClass
spec:
 rules:
 - http:
     paths:
     - path: /red
       pathType: Prefix
       backend:
         serviceName: red-service
         servicePort: 4242
     - path: /blue
       pathType: Prefix
       backend:
         serviceName: blue-service
         servicePort: 4343