apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: ingress-path
 annotations:
   kubernetes.io/ingress.class: "nginx" #指定ingressClass
spec:
    backend:
        serviceName: hello-world-service-single
        servicePort: 80