apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-depl
  name: my-depl
  namespace: test
spec:
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginxdemo
  template:
    metadata:
      labels:
        app: nginxdemo
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: "/root/hello"
            name: pvc1
      volumes:
        - name: pvc1
          persistentVolumeClaim:
            claimName: pvchost
