apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  nodeSelector:
    mongo: mongo
  containers:
    - name: redis
      image: redis
      volumeMounts:
        - mountPath: /var/lib/data
          name: vol-host
  volumes:
    - name: vol-host
      hostPath:
        path: /data/vol
        type: Directory
    - name: vol-aws
      awsElasticBlockStore:
        volumeID: uuid
        fsType: ext4