apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: google-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/gce-pd
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: pd-standard
  replication-type: noen