apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor-deployment
  namespace: bmcu
  labels:
    app: monitor-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitor-pod
  template:
    metadata:
      labels:
        app: monitor-pod
    spec:
      volumes:
        - name: config-vol
          configMap:
            name: monitor
      containers:
      - name: monitor
        image: registry.cn-beijing.aliyuncs.com/webrtc-mcu/mcu-cluster:20230208
        command: ["/bin/bash"]
        args: ["-c","npm run monitor"] #启动命令的参数
        env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                 fieldPath: status.podIP
        volumeMounts:
          - name: config-vol
            mountPath: /root/app/configs