apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudproc-deployment
  namespace: bmcu
  labels:
    app: cloudproc-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudproc-pod
  template:
    metadata:
      labels:
        app: cloudproc-pod
    spec:
      volumes:
        - name: config-vol
          configMap:
            name: cloudproc
        - name: pv-record-vol
          persistentVolumeClaim:
              claimName: pvc-record
      containers:
      - name: cloudproc
        image: registry.cn-beijing.aliyuncs.com/webrtc-mcu/cloudrecordproc:20230207
        env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                 fieldPath: status.podIP
        volumeMounts:
          - name: config-vol
            mountPath: /app/cloudrecordproc/config
          - name: pv-record-vol
            mountPath: /nas/record