apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: example-app
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: example-app
  endpoints:
  - port: web

# apiVersion: monitoring.coreos.com/v1
# kind: ServiceMonitor
# metadata:
#   name: example-app
#   labels:
#     team: frontend
# spec:
#   selector:
#     matchLabels:
#       app.kubernetes.io/name: node-exporter
#       app.kubernetes.io/vendor: kubesphere
#   endpoints:
#   - port: web