apiVersion: v1
kind: Service
metadata:
  name: hello-svc
  labels:
    app: hello-world
  namespace: svcdemo
spec:
  type: NodePort
  ports:
  - port: 8888
    nodePort: 30001
    targetPort: 80
    protocol: TCP
  selector:
    app: svcpod
