FROM busybox

WORKDIR /root
COPY ./label_node.sh /root
COPY ./jq-linux64 /bin/jq
COPY ./curl-amd64 /bin/curl

ENTRYPOINT ["/bin/sh","-c","'/root/label_node.sh'"]

# docker run --rm --name abc1 --env NodeName=node1  imagename