global:
  resolve_timeout: 1m
route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 24h
  receiver: 'email'
receivers:
- name: 'email'
  email_configs:
  - to: 'zhangxiaokai@baijiayun.com'
    from: 'mckj_zhangxk@163.com'
    smarthost: smtp.163.com:25
    auth_username: mckj_zhangxk@163.com
    auth_password: FOYNCTEMITKGPCIT
    require_tls: false

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
