apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: brtc-test-latest
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: brtc-test-latest
spec:
  type: NodePort
  selector:
    app: redis
  ports:
    - targetPort: 6379
      port: 6379