apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mpc-deployment
  labels:
    app: mpc-deployment
  namespace: brtc-test-latest
spec:
  template:
    metadata:
      name: mpc
      labels:
        app: mpc-pod
    spec:
      nodeSelector:
        mpc: mpc
      containers:
        - name: mpc
          image: {{. Values.image}}
          env:
          - name: CONFIG_APOLLO_SECRET
            value: 9d01995713a448bf9ad1b9db56f35e64
          - name: CONFIG_APOLLO_URL
            value: http://apollo-dev.baijiayun.com:8080
          - name: CONFIG_APOLLO_APPID
            value: K8sConfig
          - name: CONFIG_APOLLO_CLUSTER
            value: DEV
          - name: CONFIG_APOLLO_NAMESPACE
            value: mpc.yaml
          - name: CONFIG_APOLLO_BACKUP_PATH
            value: ./
  selector:
    matchLabels:
      app: mpc-pod