apiVersion: apps/v1
kind: Deployment
metadata:
  name: puller-deployment
  labels:
    app: puller-deployment
  namespace: brtc-test-latest
spec:
  template:
    metadata:
      name: puller
      labels:
        app: puller-pod
    spec:
      containers:
        - name: puller
          image: registry.cn-beijing.aliyuncs.com/bjy-webrtc/rtcs:test1019
          env:
          - name: CONFIG_APOLLO_SECRET
            value: 9d01995713a448bf9ad1b9db56f35e64
          - name: CONFIG_APOLLO_URL
            value: http://apollo-dev.baijiayun.com:8080
          - name: CONFIG_APOLLO_APPID
            value: K8sConfig
          - name: CONFIG_APOLLO_CLUSTER
            value: DEV
          - name: CONFIG_APOLLO_NAMESPACE
            value: rtcs-puller.yaml
          - name: CONFIG_APOLLO_BACKUP_PATH
            value: ./
  replicas: 1
  selector:
    matchLabels:
      app: puller-pod
---
apiVersion: v1
kind: Service
metadata:
  name: bj-puller-service
  namespace: brtc-test-latest
spec:
  type: NodePort
  selector:
    app: puller-pod
  ports:
    - targetPort: 8992
      port: 8992