apiVersion: v1
kind: Pod
metadata:
  name: puller-pod-demo
  namespace: test-sh
  labels:  #important
    app: puller-pod-demo
spec:
  containers:
    - name: puller
      image: 'registry.cn-beijing.aliyuncs.com/bjy-webrtc/rtcs:v2023022002'