apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      command: ["nginx"]   #用于覆盖 entrypoint ,启动命令
      args: ["-s","reload"] #启动命令的参数
      env:
        - name: APP_NAME
          value: NGINX
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP