global:
  resolve_timeout: 5m
  http_config:
    follow_redirects: true
  smtp_hello: localhost
  smtp_require_tls: true
  pagerduty_url: 'https://events.pagerduty.com/v2/enqueue'
  opsgenie_api_url: 'https://api.opsgenie.com/'
  wechat_api_url: 'https://qyapi.weixin.qq.com/cgi-bin/'
  victorops_api_url: 'https://alert.victorops.com/integrations/generic/20131114/alert/'
  telegram_api_url: 'https://api.telegram.org'
route:
  receiver: default
  group_by:
    - alertname
    - severity
  continue: false
  routes:
    - matchers:
        - alertname=node_metrics.disk
      receiver: alert-brtcs
    - matchers:
        - alertname=probe.common
      receiver: alert-brtcs
    - matchers:
        - alertname=node_metrics.cpu
      receiver: alert-brtcs
    - matchers:
        - alertname=node_metrics.memory
      receiver: alert-brtcs
    - matchers:
        - alertname=probe.node_exporter
      receiver: alert-brtcs
    - matchers:
        - alertname=probe.bandwidth.up
      receiver: alert-brtcs
    - matchers:
        - alertname=probe.bandwidth.down
      receiver: alert-brtcs

  group_wait: 30s
  group_interval: 5m
  repeat_interval: 5m
inhibit_rules:
  - source_match:
      severity: 紧急
    target_match_re:
      severity: ^(严重|普通)$
    equal:
      - instance
      - alertname
      - env
      - cluster
      - group
      - project
      - key
  - source_match:
      severity: 严重
    target_match_re:
      severity: ^(普通)$
    equal:
      - instance
      - alertname
      - env
      - cluster
      - group
      - project
      - key
receivers:
  - name: alert-brtcs
    webhook_configs:
      - send_resolved: false
        http_config:
          follow_redirects: true
        url: >-
          http://alert-webhook-service/webhook?bot_alias=alert-test-brtcs-k8s
        max_alerts: 0
