apiVersion: apps/v1
kind: Deployment
metadata:
  name: router-deployment
  labels:
    app: router-deployment
  namespace: brtc-test-latest
spec:
  template:
    metadata:
      name: router
      labels:
        app: router-pod
    spec:
      containers:
        - name: router
          image: registry.cn-beijing.aliyuncs.com/bjy-webrtc/rtcs:test1019
          env:
          - name: CONFIG_APOLLO_SECRET
            value: 9d01995713a448bf9ad1b9db56f35e64
          - name: CONFIG_APOLLO_URL
            value: http://apollo-dev.baijiayun.com:8080
          - name: CONFIG_APOLLO_APPID
            value: K8sConfig
          - name: CONFIG_APOLLO_CLUSTER
            value: DEV
          - name: CONFIG_APOLLO_NAMESPACE
            value: rtcs-router.yaml
          - name: CONFIG_APOLLO_BACKUP_PATH
            value: ./
  replicas: 1
  selector:
    matchLabels:
      app: router-pod
---
apiVersion: v1
kind: Service
metadata:
  name: rtcs-router-service
  namespace: brtc-test-latest
spec:
  type: NodePort
  selector:
    app: router-pod
  ports:
    - targetPort: 8999
      port: 8999