apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-namebased
spec:
  ingressClassName: nginx-example #很重要，不要省略，这里决定是不是可以分配到Ip
  rules:
  - host: red.example.com #red.example.com=>red-service:4242
    http:
      paths: 
      - pathType: Prefix 
        path: "/"
        backend:
          service:
            name: red-service
            port:
              number: 4242
  - host: blue.example.com #red.example.com=>blue-service:4343
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: blue-service
            port:
              number: 4343
