apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: training-common-test
spec:
  type: NodePort
  selector:
    app: redis-pod
  ports:
    - targetPort: 6379
      port: 6379
      nodePort: 30001
