apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-stateful
spec:
  template:
    metadata:
      name: redis
      labels:
        app: redis-pod
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
  replicas: 3
  selector:
    matchLabels:
      app: redis-pod
  serviceName: redis-h   #必须是 headless service Name
  podManagementPolicy: Parallel #并发创建pod
---
apiVersion: v1
kind: Service
metadata:
  name: redis-h #必须是 pod的 serviceName
  labels:
    app: redis
spec:
  ports:
  - name: http
    port: 6379
    targetPort: 6379
  clusterIP: None
  selector:
    app: redis-pod