apiVersion: apps/v1
kind: Deployment
metadata:
  name: intelroute-deployment
  labels:
    app: intelroute-deployment
  namespace: brtc-test-latest
spec:
  template:
    metadata:
      name: intelroute
      labels:
        app: intelroute-pod
    spec:
      containers:
        - name: intelroute
          image: registry.cn-beijing.aliyuncs.com/bjy-webrtc/intelroute:v2022092801
          env:
          - name: CONFIG_APOLLO_SECRET
            value: 9d01995713a448bf9ad1b9db56f35e64
          - name: CONFIG_APOLLO_URL
            value: http://apollo-dev.baijiayun.com:8080
          - name: CONFIG_APOLLO_APPID
            value: K8sConfig
          - name: CONFIG_APOLLO_CLUSTER
            value: DEV
          - name: CONFIG_APOLLO_NAMESPACE
            value: intelroute.yaml
          - name: CONFIG_APOLLO_BACKUP_PATH
            value: ./
  replicas: 1
  selector:
    matchLabels:
      app: intelroute-pod
---
apiVersion: v1
kind: Service
metadata:
  name: intelroute-service
  namespace: brtc-test-latest
spec:
  type: NodePort
  selector:
    app: intelroute-pod
  ports:
    - targetPort: 9998
      port: 9998