apiVersion: apps/v1
kind: Deployment
metadata:
  name: mpm-deployment
  labels:
    app: mpm-deployment
  namespace: brtc-test-latest
spec:
  template:
    metadata:
      name: mpm
      labels:
        app: mpm-pod
    spec:
      containers:
        - name: mpm
          image: registry.cn-beijing.aliyuncs.com/bjy-webrtc/mpm:bigroom22101901
          env:
          - name: CONFIG_APOLLO_SECRET
            value: 9d01995713a448bf9ad1b9db56f35e64
          - name: CONFIG_APOLLO_URL
            value: http://apollo-dev.baijiayun.com:8080
          - name: CONFIG_APOLLO_APPID
            value: K8sConfig
          - name: CONFIG_APOLLO_CLUSTER
            value: DEV
          - name: CONFIG_APOLLO_NAMESPACE
            value: mpm.yaml
          - name: CONFIG_APOLLO_BACKUP_PATH
            value: ./
  replicas: 1
  selector:
    matchLabels:
      app: mpm-pod
---
apiVersion: v1
kind: Service
metadata:
  name: mpm-service
  namespace: brtc-test-latest
spec:
  type: NodePort
  selector:
    app: mpm-pod