apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentinel-deployment
  labels:
    app: sentinel-deployment
  namespace: brtc-test-latest
spec:
  template:
    metadata:
      name: sentinel
      labels:
        app: sentinel-pod
    spec:
      containers:
        - name: sentinel
          image: registry.cn-beijing.aliyuncs.com/bjy-webrtc/sentinel-master:v2022101001
          env:
          - name: CONFIG_APOLLO_SECRET
            value: 9d01995713a448bf9ad1b9db56f35e64
          - name: CONFIG_APOLLO_URL
            value: http://apollo-dev.baijiayun.com:8080
          - name: CONFIG_APOLLO_APPID
            value: K8sConfig
          - name: CONFIG_APOLLO_CLUSTER
            value: DEV
          - name: CONFIG_APOLLO_NAMESPACE
            value: sentinel-master.yaml
          - name: CONFIG_APOLLO_BACKUP_PATH
            value: ./
  replicas: 1
  selector:
    matchLabels:
      app: sentinel-pod
---
apiVersion: v1
kind: Service
metadata:
  name: sentinel-service
  namespace: brtc-test-latest
spec:
  type: NodePort
  selector:
    app: sentinel-pod
  ports:
    - targetPort: 9801
      port: 9801
      name: port-9801
    - targetPort: 9804
      port: 9804
      name: port-9804