apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.16.40.25-10.16.40.25
  - 10.16.40.120-10.16.40.120
  - 10.16.40.23-10.16.40.23