apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  # securityContext:  #pod 级别
  #   runAsUser: 1000
  containers:
    - name: redis-pod
      ports:
        - containerPort: 6379
      image: redis
      securityContext:  #容器级别
        runAsUser: 1000
        capabilities:
          add:
            - "MAC_ADMIN"