apiVersion: v1
kind: Pod
metadata:
  name: affinity_demo
spec:
  containers:
    - name: nginx-pod
      image: nginx
  # nodeSelector:
  #   Size: Large
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:  #这里比 nodeSelector 更加灵活，pod可以 分配到 Large,Medium的node上面
              - key: Size
                operator: In
                values: ["Large","Medium"]