apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  namespace: xxx
spec:
  ingressClassName: nginx-example #很重要，不要省略，这里决定是不是可以分配到Ip
  rules:
  - http:
      paths:
      - path: /testpath
        pathType: Prefix
        backend:
          service:
            name: test #serviceName 
            port:
              number: 80 #ClusterIp