apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: messaging-deployment
  labels:
    app: messaging-deployment
  namespace: {{ .Values.environment }}
spec:
  template:
    metadata:
      name: messaging
      labels:
        app: messaging-pod
    spec:
      nodeSelector:
        messaging: messaging
      containers:
        - name: messaging
          image: '{{ .Values.services.message.repository }}:{{ .Values.services.message.tag }}'
          env:
          - name: CONFIG_APOLLO_SECRET
            value: {{ .Values.applo.secret }}
          - name: CONFIG_APOLLO_URL
            value: {{ .Values.applo.url }}
          - name: CONFIG_APOLLO_APPID
            value: {{ .Values.applo.appid }}
          - name: CONFIG_APOLLO_CLUSTER
            value: {{ .Values.applo.cluster }}
          - name: CONFIG_APOLLO_NAMESPACE
            value: messaging.yaml
          - name: CONFIG_APOLLO_BACKUP_PATH
            value: ./
          ports:
            - containerPort: 8886
  selector:
    matchLabels:
      app: messaging-pod
---
apiVersion: v1
kind: Service
metadata:
  name: messaging-service
  namespace: {{ .Values.environment }}
spec:
  type: NodePort
  selector:
    app: messaging-pod
  ports:
    - targetPort: 8886
      port: 8886