apiVersion: apps/v1
kind: Deployment
metadata:
  name: master-deployment
  labels:
    app: master-deployment
  namespace: {{ .Values.environment }}
spec:
  template:
    metadata:
      name: master
      labels:
        app: master-pod
    spec:
      containers:
        - name: master
          image: '{{ .Values.services.master.repository }}:{{ .Values.services.master.tag }}'
          env:
          - name: CONFIG_APOLLO_SECRET
            value: {{ .Values.applo.secret }}
          - name: CONFIG_APOLLO_URL
            value: {{ .Values.applo.url }}
          - name: CONFIG_APOLLO_APPID
            value: {{ .Values.applo.appid }}
          - name: CONFIG_APOLLO_CLUSTER
            value: {{ .Values.applo.cluster }}
          - name: CONFIG_APOLLO_NAMESPACE
            value: master.yaml
          - name: CONFIG_APOLLO_BACKUP_PATH
            value: ./
  replicas: 1
  selector:
    matchLabels:
      app: master-pod
---
apiVersion: v1
kind: Service
metadata:
  name: master-service
  namespace: {{ .Values.environment }}
spec:
  type: NodePort
  selector:
    app: master-pod
  ports:
    - targetPort: 8885
      port: 8885