apiVersion: apps/v1
kind: Deployment
metadata:
  name: brtc-admin-deployment
  labels:
    app: brtc-admin-deployment
  namespace: {{ .Values.environment }}
spec:
  template:
    metadata:
      name: brtc-admin
      labels:
        app: brtc-admin-pod
    spec:
      {{- with .Values.services.admin }}

      containers:
        - name: brtc-admin
          image: '{{.repository}}:{{.tag}}'
          env:
            - name: ADMINURL
              value: 'http://master-service:8885'
            - name: INTELROUTE
              value: 'http://intelroute-service:9998'
            - name: ADMINPORT
              value: '8083'
            - name: VUE_APP_PUBLIC_PATH
              value: '/admin/'
            - name: TOPOVIEW
              value: ''
        {{- end }}
  replicas: 1
  selector:
    matchLabels:
      app: brtc-admin-pod
---
apiVersion: v1
kind: Service
metadata:
  name: brtc-admin-service
  namespace: {{ .Values.environment }}
spec:
  type: NodePort
  selector:
    app: brtc-admin-pod
  ports:
    - targetPort: 8083
      port: 8083