apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdemo-deployment
  labels:
    app: webdemo-deployment
  namespace: {{ .Values.environment }}
spec:
  template:
    metadata:
      name: webdemo
      labels:
        app: webdemo-pod
    spec:
    {{-  with .Values.services.webdemo }}
      containers:
        - name: webdemo
          image: '{{ .repository }}:{{ .tag }}'
          env:
          - name: JWT
            value: {{ .jwt }}
          - name: MASTER
            value: {{ .master }}
          - name: PORT
            value: '{{ .port }}'
          - name: APPID
            value: {{ .appid }}
    {{- end}}
  selector:
    matchLabels:
      app: webdemo-pod

---
apiVersion: v1
kind: Service
metadata:
  name: webdemo-service
  namespace: {{ .Values.environment }}
spec:
  type: NodePort
  selector:
    app: webdemo-pod
  {{-  with .Values.services.webdemo }}
  ports:
    - targetPort: {{ .port }}
      port: {{ .port }}
  {{- end}}