apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentinel-deployment
  labels:
    app: sentinel-deployment
  namespace: {{ .Values.environment }}
spec:
  template:
    metadata:
      name: sentinel
      labels:
        app: sentinel-pod
    spec:
      containers:
        - name: sentinel
          image: '{{ .Values.services.sentinelMaster.repository }}:{{ .Values.services.sentinelMaster.tag }}'
          env:
          - name: CONFIG_APOLLO_SECRET
            value: {{ .Values.applo.secret }}
          - name: CONFIG_APOLLO_URL
            value: {{ .Values.applo.url }}
          - name: CONFIG_APOLLO_APPID
            value: {{ .Values.applo.appid }}
          - name: CONFIG_APOLLO_CLUSTER
            value: {{ .Values.applo.cluster }}
          - name: CONFIG_APOLLO_NAMESPACE
            value: sentinel-master.yaml
          - name: CONFIG_APOLLO_BACKUP_PATH
            value: ./
  replicas: {{ default 1 .Values.services.sentinelMaster.replicas}}
  selector:
    matchLabels:
      app: sentinel-pod
---
apiVersion: v1
kind: Service
metadata:
  name: sentinel-service
  namespace: {{ .Values.environment }}
spec:
  type: NodePort
  selector:
    app: sentinel-pod
  ports:
    - targetPort: 9801
      port: 9801
      name: port-9801
    - targetPort: 9804
      port: 9804
      name: port-9804