apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mpc-deployment
  labels:
    app: mpc-deployment
  namespace: {{ .Values.environment }}
spec:
  template:
    metadata:
      name: mpc
      labels:
        app: mpc-pod
    spec:
      # nodeSelector:
      #   mpc: mpc
      containers:
        - name: mpc
          image: '{{ .Values.services.mpc.repository }}:{{ .Values.services.mpc.tag }}'
          env:
          - name: CONFIG_APOLLO_SECRET
            value: {{ $.Values.applo.secret |quote }}
          - name: CONFIG_APOLLO_URL
            value: {{ $.Values.applo.url |quote  }}
          - name: CONFIG_APOLLO_APPID
            value: {{ $.Values.applo.appid |quote }}
          - name: CONFIG_APOLLO_CLUSTER
            value: {{ $.Values.applo.cluster |quote }}
          - name: CONFIG_APOLLO_NAMESPACE
            value: mpc.yaml
          - name: CONFIG_APOLLO_BACKUP_PATH
            value: ./
  selector:
    matchLabels:
      app: mpc-pod
---
apiVersion: v1
kind: Service
metadata:
  name: mpc-service
  namespace: {{ .Values.environment }}
spec:
  type: NodePort
  selector:
    app: mpc-pod
  ports:
  {{- with .Values.services.mpc }}
    - targetPort: {{ default 8082 .port }}
      port:  {{ default 8082  .port }}
      nodePort:  {{ default 8082  .port }}    
  {{- end }}
