apiVersion: apps/v1
kind: Deployment
metadata:
  name: puller-deployment
  labels:
    app: puller-deployment
  namespace: {{ .Values.environment }}
spec:
  template:
    metadata:
      name: puller
      labels:
        app: puller-pod
    spec:
      containers:
        - name: puller
          image: '{{ .Values.services.puller.repository }}:{{ .Values.services.puller.tag }}'
          env:
          - name: CONFIG_APOLLO_SECRET
            value:  {{ .Values.applo.secret }}
          - name: CONFIG_APOLLO_URL
            value: {{ .Values.applo.url }}
          - name: CONFIG_APOLLO_APPID
            value: {{ .Values.applo.appid }}
          - name: CONFIG_APOLLO_CLUSTER
            value: {{ .Values.applo.cluster }}
          - name: CONFIG_APOLLO_NAMESPACE
            value: rtcs-puller.yaml
          - name: CONFIG_APOLLO_BACKUP_PATH
            value: ./
  replicas: {{ default 1 .Values.services.puller.replicas}}
  selector:
    matchLabels:
      app: puller-pod
---
apiVersion: v1
kind: Service
metadata:
  name: puller-service
  namespace: {{ .Values.environment }}
spec:
  type: NodePort
  selector:
    app: puller-pod
  ports:
    - targetPort: 8992
      port: 8992