apiVersion: apps/v1
kind: Deployment
metadata:
  name: mpm-deployment
  labels:
    app: mpm-deployment
  namespace: {{ .Values.environment }}
spec:
  template:
    metadata:
      name: mpm
      labels:
        app: mpm-pod
    spec:
      containers:
        - name: mpm
          image: '{{ .Values.services.mpm.repository }}:{{ .Values.services.mpm.tag }}'
          env:
          - name: CONFIG_APOLLO_SECRET
            value: {{ .Values.applo.secret }}
          - name: CONFIG_APOLLO_URL
            value: {{ .Values.applo.url }}
          - name: CONFIG_APOLLO_APPID
            value: {{ .Values.applo.appid }}
          - name: CONFIG_APOLLO_CLUSTER
            value: {{ .Values.applo.cluster }}
          - name: CONFIG_APOLLO_NAMESPACE
            value: mpm.yaml
          - name: CONFIG_APOLLO_BACKUP_PATH
            value: ./
  replicas: {{ default 1 .Values.services.mpm.replicas}}
  selector:
    matchLabels:
      app: mpm-pod