apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: msms-deployment
  labels:
    app: msms-deployment
  namespace: {{ .Values.environment }}
spec:
  template:
    metadata:
      name: msms
      labels:
        app: msms-pod
    spec:
      # nodeSelector:
      #   ms: ms
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: msms
          image: '{{ .Values.services.msms.repository }}:{{ .Values.services.msms.tag }}'
          env:
          - name: CONFIG_APOLLO_SECRET
            value: {{ $.Values.applo.secret }}
          - name: CONFIG_APOLLO_URL
            value: {{ $.Values.applo.url }}
          - name: CONFIG_APOLLO_APPID
            value: {{ $.Values.applo.appid }}
          - name: CONFIG_APOLLO_CLUSTER
            value: {{ $.Values.applo.cluster }}

         {{- with .Values.services.msms }}
          - name: CONFIG_APOLLO_NAMESPACE
            value: ms2_conf.json
          - name: CONFIG_APOLLO_BACKUP_PATH
            value: ./
          - name: MALLOC_TRIM_THRESHOLD_
            value: "65535"
          - name: MALLOC_MMAP_THRESHOLD_
            value: "65535"
          - name: CFG_CENTER
            value: "TRUE"
          - name: MS_PORT
            value: "{{ .port }}"
          - name: GET_CONTAINER_CMD
            value: {{ .containCmd | quote }}
          - name: PUB_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: INNER_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: PULLER_URL
            value: "http://puller-service:8992"
        {{- end }}
        - name: sagent
          image: '{{ .Values.services.sentinelAgent.repository }}:{{ .Values.services.sentinelAgent.tag }}'
          env:
          - name: CONFIG_APOLLO_SECRET
            value: {{ $.Values.applo.secret }}
          - name: CONFIG_APOLLO_URL
            value: {{ $.Values.applo.url }}
          - name: CONFIG_APOLLO_APPID
            value: {{ $.Values.applo.appid }}
          - name: CONFIG_APOLLO_CLUSTER
            value: {{ $.Values.applo.cluster }}
          - name: CONFIG_APOLLO_NAMESPACE
            value: sentinel-agent.yaml
  selector:
    matchLabels:
      app: msms-pod