---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-deployment
  namespace: {{ .Values.environment }}
spec:
  template:
    metadata:
      name: nats-pod
      labels:
        app: nats-pod
        author: zhangxk
    spec:
      containers:
        - name: nats-pod
          image: nats:latest
  selector:
    matchLabels:
      app: nats-pod
      author: zhangxk
  replicas: 1

---
kind: Service
apiVersion: v1
metadata:
  name: nats-service
  namespace: {{ .Values.environment }}
  labels:
    app: nats-service
  annotations:
    kubesphere.io/creator: admin
spec:
  ports:
    - name: http-4222
      protocol: TCP
      port: 4222
      targetPort: 4222
    - name: http-8222
      protocol: TCP
      port: 8222
      targetPort: 8222
  selector:
    app: nats-pod
    author: zhangxk
  type: NodePort
